service:
  name: aws-nodejs-typescript

# Add the serverless-webpack plugin
plugins:
  - serverless-offline
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs6.10

functions:
  bell:
    handler: handler.bell
    events:
      - http:
          method: get
          path: bell
